<table background=""><tr><td align="left" width="80%" ><b><font size=18>Python Test 100</font></b><br><font size=12>Group Pandas 2</font></td>
<td><img src="https://d12swbtw719y4s.cloudfront.net/images/4YsuGDYU/eBH7C3G0bPeRy3QXUWQV/Cover_Art_Remake.jpeg?w=200.png"></td></tr></table>

In [1]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
def ddd():
    """
    # returns a simple pandas DataFrame - useful for quick tests
    """
    nrows = 7
    aa = pd.DataFrame({
        'ii':[0,1,2,3,4,5,np.nan],                                  # float64
        'i1':[6,5,4,3,2,1,0],
        'i2':[6,5,4,4,1,1,0],
        'ff':[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0],                      # float64
        'f1':[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006],
        'f2':[1.11,2.22,3.33,4.44,5.55,7.77,9.99],
        'ss':['s0','s1','狗','汽车',np.nan,'s5','s6'],               # dtype=object, np.nan is float64
        's1':np.array(['s0','s1','s2','s2',np.nan,'s5','s6'],
                      dtype=np.str), # dtype=object, 'nan' is string
        's2':['1.11','2.22','3.33','4.44','5.55','7.77','9.99'],
        'bb':[True, False, True, False, np.nan, False, True],       # dtype=object, np.nan is float64
        'b1':[True, False, True, False, True, False, True],         # dtype=bool
        'xx':range(nrows),
        'yy':[x*50 + 60 + np.random.randn() for x in range(nrows)]
    })

    return aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']]

### Question 1

Changing the order of columns in a DataFrame.

#### Answer

In [3]:
aa = pd.DataFrame({
    'a' : [0,1,2],
    'b' : [0,2,4],
    'c' : [0,1,3]
})
display(aa)

col_list_ordered = ['b','c','a']    # When you reorder using these methods, the data in the columns also shift along with names 
aa = aa[col_list_ordered]
display(aa)

print('-'*40)

# or (notice double-brackets)
aa = aa[['c','b','a']]
display(aa)

aa.columns = ['b','a','c']    # Rename columns without changing contents of the columns
display(aa)

   a  b  c
0  0  0  0
1  1  2  1
2  2  4  3

   b  c  a
0  0  0  0
1  2  1  1
2  4  3  2

----------------------------------------

   c  b  a
0  0  0  0
1  1  2  1
2  3  4  2

   b  a  c
0  0  0  0
1  1  2  1
2  3  4  2

### Question 2

Show how to check if a dataframe has a column with a particular name

#### Answer

In [4]:
aa = ddd()
display(aa.head())
aa.
if 'i2' in aa.columns:
    print("true")

SyntaxError: invalid syntax (<ipython-input-4-65bd34a921d2>, line 3)

### Question 3

Select rows of a pandas DataFrame which have null values (in any column)

#### Answer

In [5]:
mask = False
def rows_with_nulls(df):
    #mask=pd.Series(data = [False]*len(df), index = df.index)
    global mask
    # mask = False
    for col in df.columns:
        print(mask)
        mask = mask | df[col].isnull()

    return df.loc[mask,:].copy()

aa = ddd()
display(aa)
print('-' * 40)
bb = rows_with_nulls(aa)
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.890119
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  111.197582
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.817702
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.472268
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.479949
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.792351
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.596891

----------------------------------------
False
0    False
1    False
2    False
3    False
4    False
5    False
6     True
Name: ii, dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
dtype: bool

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.472268
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.479949
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.596891

In [6]:
    mask=pd.Series

### Question 4

Show how to substitute for null values 
- in a column 
- in the whole dataframe

#### Answer

In [7]:
# IN COLUMN
aa = ddd()
display(aa)
aa['ss'] = aa.ss.fillna('hello')
#          aa.ss.fillna(0)
#          aa.ss.fillna('-')
display(aa)
print('-'*40)

# IN ENTIRE DATAFRAME
aa = ddd()
aa.fillna(0, inplace=True)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.139296
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.121513
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.052170
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.402672
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.654806
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.342666
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.917386

    ii  i1  i2   ff        f1    f2     ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11     s0   s0  1.11   True   True   0   59.139296
1  1.0   5   5  1.0  1.010000  2.22     s1   s1  2.22  False  False   1  110.121513
2  2.0   4   4  2.0  2.002000  3.33      狗   s2  3.33   True   True   2  160.052170
3  3.0   3   4  NaN  3.000300  4.44     汽车   s2  4.44  False  False   3  210.402672
4  4.0   2   1  4.0  4.000040  5.55  hello  nan  5.55    NaN   True   4  259.654806
5  5.0   1   1  5.0  5.000005  7.77     s5   s5  7.77  False  False   5  310.342666
6  NaN   0   0  6.0  6.000001  9.99     s6   s6  9.99   True   True   6  359.917386

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0   s0  1.11   True   True   0   59.364356
1  1.0   5   5  1.0  1.010000  2.22  s1   s1  2.22  False  False   1  111.703202
2  2.0   4   4  2.0  2.002000  3.33   狗   s2  3.33   True   True   2  159.962549
3  3.0   3   4  0.0  3.000300  4.44  汽车   s2  4.44  False  False   3  210.012370
4  4.0   2   1  4.0  4.000040  5.55   0  nan  5.55      0   True   4  261.360303
5  5.0   1   1  5.0  5.000005  7.77  s5   s5  7.77  False  False   5  309.891357
6  0.0   0   0  6.0  6.000001  9.99  s6   s6  9.99   True   True   6  360.324542

### Question 5

Can an integer column in pandas DataFrame have a NaN value?

#### Answer

```
No. Float column can.
If you insert a NaN value into integer column, 
the column type will be changed to float64
```

In [8]:
aa = ddd()
display(aa)
print(aa.i1.dtype)
aa.loc[1,'i1'] = np.NaN
print(aa.i1.dtype)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.962974
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  111.860676
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.036907
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.357141
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  262.380916
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.087558
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.501286

int64
float64

    ii   i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0  6.0   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.962974
1  1.0  NaN   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  111.860676
2  2.0  4.0   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.036907
3  3.0  3.0   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.357141
4  4.0  2.0   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  262.380916
5  5.0  1.0   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.087558
6  NaN  0.0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.501286

### Question 6

Show how to convert value type of a column to int64 or float64

#### Answer

In [9]:
aa = ddd()
display(aa)
print(aa.i1.dtype)
aa['i1'] = aa.i1.astype(np.float64)
print(aa.i1.dtype)
display(aa)
aa['i1'] = aa.i1.astype(np.int64)
print(aa.i1.dtype)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.213353
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  108.769122
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.453021
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.042647
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.786892
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.164082
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.840290

int64
float64

    ii   i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0  6.0   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.213353
1  1.0  5.0   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  108.769122
2  2.0  4.0   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.453021
3  3.0  3.0   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.042647
4  4.0  2.0   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.786892
5  5.0  1.0   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.164082
6  NaN  0.0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.840290

int64

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.213353
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  108.769122
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.453021
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.042647
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.786892
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.164082
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.840290

### Question 7 (Exercise)

Do the following:
- Take first several rows for a dataframe (regardless of index)
- Take last several rows of a dataframe (regardless of index)
- Take group of rows in the middle (regardless of index)
- Take one row as a list (first / last / middle)

#### Answer

In [10]:
print("first rows as dataframe")
aa = ddd()
print(aa.head())  # by default takes up to 5 rows
print('-'*40)
print(aa.head(2)) 
print('-'*40)
print(aa[:3]) # slice - same as .head(3)
print('-'*40)
print("last rows as dataframe")
print(aa.tail())
print('-'*40)
print(aa[-5:])
print('-'*40)

print("rows in the middle as dataframe")
print(aa[2:4])

print("Take one row as a list (first / last / middle)")
print(aa.loc[aa.index[0]].tolist())
print(aa.loc[aa.index[-1]].tolist())
print(aa.loc[aa.index[3]].tolist())

first rows as dataframe
    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.00000  1.11   s0   s0  1.11   True   True   0   57.872982
1  1.0   5   5  1.0  1.01000  2.22   s1   s1  2.22  False  False   1  108.434774
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  158.337818
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  210.708988
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  261.407305
----------------------------------------
    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.00  1.11  s0  s0  1.11   True   True   0   57.872982
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  108.434774
----------------------------------------
    ii  i1  i2   ff     f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000  1.11  s0  s0  1.11   True   True   0   57.872982
1  1.0   5   5  1.0  1.010  2.22  s1  s1  2.22  False  False   1  108.434774
2  2.0   4   4  2.0  2.002  3.33   狗  s2  3.33   True   True   2  158.337818
----------------------------------------
last rows as dataframe
    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.337818
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.708988
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.407305
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.960690
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.922786
----------------------------------------
    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.337818
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.708988
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.407305
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.960690
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.922786
----------------------------------------
rows in the middle as dataframe
    ii  i1  i2   ff      f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.0020  3.33   狗  s2  3.33   True   True   2  158.337818
3  3.0   3   4  NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  210.708988
Take one row as a list (first / last / middle)
[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 57.872982373189586]
[nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 360.92278609340207]
[3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 210.70898801141155]

### Question 8

Show how to take the first row of a DataFrame as a list or dict

#### Answer

In [11]:
aa = ddd()
#aa.index = [6,5,4,3,2,1,0]
display(aa)
mylist = aa.loc[aa.index[0]].tolist()
mydict = aa.loc[aa.index[4]].to_dict()
print(mylist)
print(mydict)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.233534
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.925851
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.942354
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.739900
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.015953
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.818391
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.320331

[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 61.23353401004458]
{'ii': 4.0, 'i1': 2, 'i2': 1, 'ff': 4.0, 'f1': 4.00004, 'f2': 5.55, 'ss': nan, 's1': 'nan', 's2': '5.55', 'bb': nan, 'b1': True, 'xx': 4, 'yy': 258.01595300503044}

### Question 9

Show the following ways of combining two pandas DataFrames
- merge
- append
- concat
- combine_first

#### Answer

In [12]:
# Pandas DataFrames are similar to SQL database tables.
# they can be joined using two mechanisms: join() and merge()
# join() does joining on indexes, merge() - on columns
# I usually use merge()
#
# df_joined = merge(df1, df2, on=[columns], how='inner')
# df_joined = merge(df1, df2, on=[columns], how='left')


# This is exactly like joining 2 tables in SQL
# you can use inner join ('inner') or left outer join ('left')

In [13]:
# append allows to append two DataFrames vertically one on top of another
# 
df = aa.append(bb,ignore_index=True)
display(df)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.233534
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.925851
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.942354
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.739900
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.015953
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.818391
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.320331
7  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.472268
8  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.479949
9  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.596891

In [14]:
# concat() allows to stack DataFrames vertically (default) or horizontally
#   concat([s1,s2,s3])      - stacks together objects along an axis (vertically)
#   concat([aa,bb],axis=1) - stacking horizontally

In [17]:
aa = ddd()
bb = ddd()
display(aa)
cc = pd.merge(aa, bb, on='i2')
display(cc)
# pd.merge?

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.584032
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.980946
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.965790
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.492857
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.294781
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.051500
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  357.769279

    ii_x  i1_x  i2  ff_x      f1_x  f2_x ss_x s1_x  s2_x   bb_x     ...      ff_y      f1_y  f2_y  ss_y  s1_y  s2_y   bb_y   b1_y xx_y        yy_y
0    0.0     6   6   0.0  0.000000  1.11   s0   s0  1.11   True     ...       0.0  0.000000  1.11    s0    s0  1.11   True   True    0   61.041801
1    1.0     5   5   1.0  1.010000  2.22   s1   s1  2.22  False     ...       1.0  1.010000  2.22    s1    s1  2.22  False  False    1  110.095793
2    2.0     4   4   2.0  2.002000  3.33    狗   s2  3.33   True     ...       2.0  2.002000  3.33     狗    s2  3.33   True   True    2  160.454337
3    2.0     4   4   2.0  2.002000  3.33    狗   s2  3.33   True     ...       NaN  3.000300  4.44    汽车    s2  4.44  False  False    3  209.331294
4    3.0     3   4   NaN  3.000300  4.44   汽车   s2  4.44  False     ...       2.0  2.002000  3.33     狗    s2  3.33   True   True    2  160.454337
5    3.0     3   4   NaN  3.000300  4.44   汽车   s2  4.44  False     ...       NaN  3.000300  4.44    汽车    s2  4.44  False  False    3  209.331294
6    4.0     2   1   4.0  4.000040  5.55  NaN  nan  5.55    NaN     ...       4.0  4.000040  5.55   NaN   nan  5.55    NaN   True    4  261.095091
7    4.0     2   1   4.0  4.000040  5.55  NaN  nan  5.55    NaN     ...       5.0  5.000005  7.77    s5    s5  7.77  False  False    5  308.319460
8    5.0     1   1   5.0  5.000005  7.77   s5   s5  7.77  False     ...       4.0  4.000040  5.55   NaN   nan  5.55    NaN   True    4  261.095091
9    5.0     1   1   5.0  5.000005  7.77   s5   s5  7.77  False     ...       5.0  5.000005  7.77    s5    s5  7.77  False  False    5  308.319460
10   NaN     0   0   6.0  6.000001  9.99   s6   s6  9.99   True     ...       6.0  6.000001  9.99    s6    s6  9.99   True   True    6  360.185720

[11 rows x 25 columns]

In [18]:
# df1.combine_first(df2)
#   Combine two DataFrames
#   uses df2 to fill-in null values in df1

df1 = pd.DataFrame([[1, np.nan]])
df2 = pd.DataFrame([[3, 4]])
aa = df1.combine_first(df2)
display(df1)
print('---------')
display(df2)
print('---------')
display(aa)

   0   1
0  1 NaN

---------

   0  1
0  3  4

---------

   0    1
0  1  4.0

### Question 10

Show the following:
- pandas stack()/unstack() functions
- grouping by mask

#### Answer

In [19]:
xx = pd.DataFrame(
    [ ["Jan","name1",1,2,3],   
      ["Jan","name2",4,5,6],
      ["Mar","name1",11,12,13],
      ["Mar","name2",14,15,16] 
    ],
    columns=["Month","Name","c1","c2","c3"])

display(xx)
print('-----------------------------')
# convert Month and Name into index
yy = xx.set_index(["Month","Name"])
display(yy)
print('-----------------------------')
# Stack all remaining columns (c1,c2,c3) - make a one-column Series
yy = xx.set_index(["Month","Name"]).stack()
display(yy)
print('-----------------------------')
yy = xx.set_index(["Month","Name"]).stack().unstack('Month')
display(yy)
print('-----------------------------')

mask = yy.Jan > 3
zz = yy.groupby(by=mask).sum()
display(zz)

  Month   Name  c1  c2  c3
0   Jan  name1   1   2   3
1   Jan  name2   4   5   6
2   Mar  name1  11  12  13
3   Mar  name2  14  15  16

-----------------------------

             c1  c2  c3
Month Name
Jan   name1   1   2   3
      name2   4   5   6
Mar   name1  11  12  13
      name2  14  15  16

-----------------------------

Month  Name
Jan    name1  c1     1
              c2     2
              c3     3
       name2  c1     4
              c2     5
              c3     6
Mar    name1  c1    11
              c2    12
              c3    13
       name2  c1    14
              c2    15
              c3    16
dtype: int64

-----------------------------

Month     Jan  Mar
Name
name1 c1    1   11
      c2    2   12
      c3    3   13
name2 c1    4   14
      c2    5   15
      c3    6   16

-----------------------------

Month  Jan  Mar
Jan
False    6   36
True    15   45

### Question 11

Show use of pandas DataFrame.pivot()

#### Answer

In [20]:
aa = pd.DataFrame(
    { 'foo' : 3*['one'] + 3*['two'],
      'bar' : 2*['A','B','C'],
      'baz' : [1,2,3,4,5,6]
    }
)

aa = aa[['foo','bar','baz']]
display(aa)
print("---------------")
#       foo bar  baz
#    0  one   A    1
#    1  one   B    2
#    2  one   C    3
#    3  two   A    4
#    4  two   B    5
#    5  two   C    6

display(aa.pivot('foo','bar','baz'))
print("---------------")
display(aa.pivot('foo', 'bar')['baz'])

   foo bar  baz
0  one   A    1
1  one   B    2
2  one   C    3
3  two   A    4
4  two   B    5
5  two   C    6

---------------

bar  A  B  C
foo
one  1  2  3
two  4  5  6

---------------

bar  A  B  C
foo
one  1  2  3
two  4  5  6

### Question 12

Create a pandas DataFrame and populate with data
- from dict of columns,
- from list
- from numpy array
- from list of series
- from list of lists

#### Answer

In [45]:
df = pd.DataFrame({
    'x'  : 3 * ['a'] + 2 * ['b'],
    'nn' : np.arange(5, dtype=np.float64), 
    'y'  : np.random.rand(5),
    'z'  : range(5)
})


df = pd.DataFrame([[1,2,3]], columns=['A','B','C'])

df = pd.DataFrame(
    np.arange(12).reshape((3,4)),
    index = ['A','B','C'],
    columns = ['AA','BB','CC','DD']
)

display(df)
nrows  = 10
ncols  =  5
mydata = np.random.rand(nrows, ncols)

#mydata = np.random.randn(nrows, ncols)

aa = pd.DataFrame(data=mydata)
aa = pd.DataFrame(data=mydata, 
                  index=range(nrows), 
                  columns=[chr(65+x)*2 for x in range(ncols)])

aa = pd.DataFrame( np.random.normal(size=12).reshape((3,4)), 
                   index = ['A','B','C'], 
                   columns = ['AA','BB','CC','DD'] )

s1 = pd.Series({'x':1,'y':2})
s2 = pd.Series({'x':3,'y':4})
aa = pd.DataFrame([s1,s2])   # s1 and s2 - rows

mydata = [[1,2],[3,4],[5,6]]
aa = pd.DataFrame(mydata, columns=['AA','BB'])

   AA  BB  CC  DD
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11

### Question 13

Generate random numbers to populate a DataFrame
<br>use Numpy  np.random

#### Answer

In [55]:
# np.random.<TAB>
# np.random.seed(int)
Ncols = 4
Nrows = 5

# several ways to generate numbers
data = np.random.rand(Nrows, Ncols)
data = np.random.randn(Nrows, Ncols)
data = np.random.normal(size=Nrows*Ncols).reshape(Nrows,Ncols)
data = np.random.normal(size=Nrows*Ncols, loc=10.0, scale=1.0).reshape(Nrows,Ncols)

aa = pd.DataFrame(data, columns = ['c1','c2','c3','c4'] )
print(aa)

          c1         c2         c3         c4
0  10.604199   9.865115   9.786272  11.922936
1   9.195179  10.091632  10.142076   9.880580
2  10.812316  10.756919  10.481395   9.655473
3  10.244832   9.909407  10.374019  10.307013
4   8.777709   9.473171  10.514459   8.921822

## Question 13a

transform a row using flexible 
    custom function operating on all columns

In [56]:
list(range(4,-1,-1))

[4, 3, 2, 1, 0]

In [59]:
df = pd.DataFrame({'aa':range(5), 'bb':range(5)})
print(df) # 5 rows
print('-'*40)

   aa  bb
0   0   0
1   1   1
2   2   2
3   3   3
4   4   4
----------------------------------------

In [60]:
# ------------------------------------
def myfunc(df):
    """ This function is applied to a subset (groupping) of rows"""
    df['lev'] = df['aa'].map(lambda x: str(x**2)) + '_' + df['bb'].map(lambda x: str(x**2))
    df['bb'] = df.bb**3
    return df

df2 = df.groupby(df.bb, as_index=False).apply(myfunc)
print(df2)

   aa  bb    lev
0   0   0    0_0
1   1   1    1_1
2   2   8    4_4
3   3  27    9_9
4   4  64  16_16

### Question 14

Show how to iterate through rows of pandas DataFrame

#### Answer

In [62]:
aa=ddd()
for rr in aa.itertuples(): 
    print(rr)

print('-'*40)
for rr in aa.itertuples(index=False): 
    print(rr)

# pd.DataFrame.iterrows()  - a generator
#     yields tuple (index, row_as_Series)
#     Slow, because needs to create a Series from each row.
  
print('-'*40)
for row in aa.iterrows():
    ind = row[0]
    ser = row[1]
    cols = list(ser.index)
    vals = list(ser)
    print("ind = ",ind,", vals = ",vals)

print('-'*40)
for row in aa.iterrows():
    print(row[1].values)
print('-'*40)
for row in aa.iterrows():
    print(list(row[1].values))

# Another way:
# for ii in aa.index: 
#     do_something(aa.ix[ii])

Pandas(Index=0, ii=0.0, i1=6, i2=6, ff=0.0, f1=0.0, f2=1.11, ss='s0', s1='s0', s2='1.11', bb=True, b1=True, xx=0, yy=58.275673413243226)
Pandas(Index=1, ii=1.0, i1=5, i2=5, ff=1.0, f1=1.01, f2=2.22, ss='s1', s1='s1', s2='2.22', bb=False, b1=False, xx=1, yy=108.86709875779029)
Pandas(Index=2, ii=2.0, i1=4, i2=4, ff=2.0, f1=2.002, f2=3.33, ss='狗', s1='s2', s2='3.33', bb=True, b1=True, xx=2, yy=160.169892967744)
Pandas(Index=3, ii=3.0, i1=3, i2=4, ff=nan, f1=3.0003, f2=4.44, ss='汽车', s1='s2', s2='4.44', bb=False, b1=False, xx=3, yy=207.36738026697986)
Pandas(Index=4, ii=4.0, i1=2, i2=1, ff=4.0, f1=4.00004, f2=5.55, ss=nan, s1='nan', s2='5.55', bb=nan, b1=True, xx=4, yy=259.1112515624355)
Pandas(Index=5, ii=5.0, i1=1, i2=1, ff=5.0, f1=5.000005, f2=7.77, ss='s5', s1='s5', s2='7.77', bb=False, b1=False, xx=5, yy=309.14580083743874)
Pandas(Index=6, ii=nan, i1=0, i2=0, ff=6.0, f1=6.0000006, f2=9.99, ss='s6', s1='s6', s2='9.99', bb=True, b1=True, xx=6, yy=360.33974495539485)
----------------------------------------
Pandas(ii=0.0, i1=6, i2=6, ff=0.0, f1=0.0, f2=1.11, ss='s0', s1='s0', s2='1.11', bb=True, b1=True, xx=0, yy=58.275673413243226)
Pandas(ii=1.0, i1=5, i2=5, ff=1.0, f1=1.01, f2=2.22, ss='s1', s1='s1', s2='2.22', bb=False, b1=False, xx=1, yy=108.86709875779029)
Pandas(ii=2.0, i1=4, i2=4, ff=2.0, f1=2.002, f2=3.33, ss='狗', s1='s2', s2='3.33', bb=True, b1=True, xx=2, yy=160.169892967744)
Pandas(ii=3.0, i1=3, i2=4, ff=nan, f1=3.0003, f2=4.44, ss='汽车', s1='s2', s2='4.44', bb=False, b1=False, xx=3, yy=207.36738026697986)
Pandas(ii=4.0, i1=2, i2=1, ff=4.0, f1=4.00004, f2=5.55, ss=nan, s1='nan', s2='5.55', bb=nan, b1=True, xx=4, yy=259.1112515624355)
Pandas(ii=5.0, i1=1, i2=1, ff=5.0, f1=5.000005, f2=7.77, ss='s5', s1='s5', s2='7.77', bb=False, b1=False, xx=5, yy=309.14580083743874)
Pandas(ii=nan, i1=0, i2=0, ff=6.0, f1=6.0000006, f2=9.99, ss='s6', s1='s6', s2='9.99', bb=True, b1=True, xx=6, yy=360.33974495539485)
----------------------------------------
ind =  0 , vals =  [0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 58.275673413243226]
ind =  1 , vals =  [1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.86709875779029]
ind =  2 , vals =  [2.0, 4, 4, 2.0, 2.002, 3.33, '狗', 's2', '3.33', True, True, 2, 160.169892967744]
ind =  3 , vals =  [3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 207.36738026697986]
ind =  4 , vals =  [4.0, 2, 1, 4.0, 4.00004, 5.55, nan, 'nan', '5.55', nan, True, 4, 259.1112515624355]
ind =  5 , vals =  [5.0, 1, 1, 5.0, 5.000005, 7.77, 's5', 's5', '7.77', False, False, 5, 309.14580083743874]
ind =  6 , vals =  [nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 360.33974495539485]
----------------------------------------
>>>> <class 'tuple'>
[0.0 6 6 0.0 0.0 1.11 's0' 's0' '1.11' True True 0 58.275673413243226]
>>>> <class 'tuple'>
[1.0 5 5 1.0 1.01 2.22 's1' 's1' '2.22' False False 1 108.86709875779029]
>>>> <class 'tuple'>
[2.0 4 4 2.0 2.002 3.33 '狗' 's2' '3.33' True True 2 160.169892967744]
>>>> <class 'tuple'>
[3.0 3 4 nan 3.0003 4.44 '汽车' 's2' '4.44' False False 3 207.36738026697986]
>>>> <class 'tuple'>
[4.0 2 1 4.0 4.00004 5.55 nan 'nan' '5.55' nan True 4 259.1112515624355]
>>>> <class 'tuple'>
[5.0 1 1 5.0 5.000005 7.77 's5' 's5' '7.77' False False 5
 309.14580083743874]
>>>> <class 'tuple'>
[nan 0 0 6.0 6.0000006 9.99 's6' 's6' '9.99' True True 6
 360.33974495539485]
----------------------------------------
[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 58.275673413243226]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.86709875779029]
[2.0, 4, 4, 2.0, 2.002, 3.33, '狗', 's2', '3.33', True, True, 2, 160.169892967744]
[3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 207.36738026697986]
[4.0, 2, 1, 4.0, 4.00004, 5.55, nan, 'nan', '5.55', nan, True, 4, 259.1112515624355]
[5.0, 1, 1, 5.0, 5.000005, 7.77, 's5', 's5', '7.77', False, False, 5, 309.14580083743874]
[nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 360.33974495539485]

### Question 15

Show how to do string operations on columns

#### Answer

In [5]:
aa = pd.DataFrame({
    'ss':['aa1','bb2','cc3',np.nan],
    'ff':['  11.11  ','  22.22  ','  33.33  ','  44.44  '],
    'ii':['  11     ','  22     ','  33     ','  44     ']
})
display(aa)
# use str method on Series/Column:
# aa.ss.str.<TAB>
print(aa.ss.str.contains('bb'))
print('-'*40)
print(aa.ss.str[:2])   # first 2 characters
print('-'*40)
print(aa.ss.str.upper())
print('-'*40)
print(aa.ss.str.len())
print('-'*40)
# etc.

# using regular expression
mask = aa.ss.map(lambda x: True if re.search(r'b[23]',str(x)) else False)
print(mask)
print('-'*40)
# --------------------
# convert from string to number and back
# aa['zz'] = aa.ff.astype(np.int64) # error
aa['zz'] = aa.ff.map(lambda x: int(float(x)) if x==x else np.nan).astype(np.int64)
display(aa)
print('-'*40)

aa['zz'] = aa.ii.astype(np.int64) # works
display(aa.zz.dtype)
aa['zz'] = aa.ff.astype(np.float64) # works
aa['zz'] = aa.ii.astype(np.float64) # works
print(aa.zz.dtype)
aa['zz'] = aa.ii.str.strip().astype(float)
print(aa.zz.dtype)
aa['zz'] = aa.ii.str.strip().str[0].astype(int)
print(aa.zz.dtype)
aa['zz'] = aa.ff.astype(object)  # use this to work with a string
print(aa.zz.dtype)
aa['zz'] = aa.ff.astype(str)     # silent error?
print(aa['zz'])
print(aa.zz.dtype)

# mask = aa.ss.str.match(r'1|3') - doesn't work yet
# mask = aa.ss.get(label) # ??

    ss         ff         ii
0  aa1    11.11      11
1  bb2    22.22      22
2  cc3    33.33      33
3  NaN    44.44      44

0    False
1     True
2    False
3      NaN
Name: ss, dtype: object
----------------------------------------
0     aa
1     bb
2     cc
3    NaN
Name: ss, dtype: object
----------------------------------------
0    AA1
1    BB2
2    CC3
3    NaN
Name: ss, dtype: object
----------------------------------------
0    3.0
1    3.0
2    3.0
3    NaN
Name: ss, dtype: float64
----------------------------------------
0    False
1     True
2    False
3    False
Name: ss, dtype: bool
----------------------------------------

    ss         ff         ii  zz
0  aa1    11.11      11       11
1  bb2    22.22      22       22
2  cc3    33.33      33       33
3  NaN    44.44      44       44

----------------------------------------

dtype('int64')

float64
float64
int32
object
0      11.11
1      22.22
2      33.33
3      44.44
Name: zz, dtype: object
object

### Question 16

Make a histogram (cutting data into bins) from DataFrame

#### Answer

In [7]:
aa=np.random.normal(size=100)
print(aa)
bins=[-3, -2.5, -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5, 3]
vals = pd.cut(aa,bins)
pd.value_counts(vals)

# also look at pd.qcut

[-1.03222223  0.07047317 -1.92885538 -0.22137817  0.94718844 -0.12412968
  1.06074912 -0.56045277 -0.66354466  1.19411249 -1.14715154 -1.9180422
  0.47931464 -0.39391993  1.735385    1.13607573 -0.07556618 -0.19369959
 -0.69947116  0.21745963  0.48297496  0.08719875  0.34979797 -0.28651599
 -0.81832359  0.96028265 -0.08008014  2.08813026 -0.10764817 -0.04669723
  1.01879443  1.33655609 -0.38597281  0.60159347  1.40053135  1.12141968
 -0.8610526  -1.20194744  0.53014441  0.79319096 -0.17960473  0.38039489
  0.75551482 -0.96977491  0.07535329 -0.76384409 -1.39572892 -0.0222383
 -1.79528019  1.50224756  1.69341357 -1.00580589  0.46301971 -0.03109806
 -2.06620867  0.85958165  0.21687737 -1.32554553 -0.1288903  -0.06986749
 -0.66532103 -1.0413054   1.12237027 -0.33076956  1.43416931 -1.55720805
  1.08934006  0.67866822 -0.93272067 -0.74694868 -1.83003687  1.26867742
  0.32059273  1.35180596  0.2082686   0.3098324  -0.34728868  0.13062239
 -0.97477633  1.51042993  0.62176715 -0.10022199  0.90955028  0.48459887
  0.42049354 -2.34292766  0.78285813  0.75627513  0.06044062  0.81461924
  1.16232644  0.41301126  0.13586286  1.98642604  1.12533755  1.92399847
  0.88331829  1.78906966 -0.27199566  0.98018551]

(0.0, 0.5]      19
(-0.5, 0.0]     19
(0.5, 1.0]      15
(1.0, 1.5]      14
(-1.0, -0.5]    11
(1.5, 2.0]       7
(-1.5, -1.0]     7
(-2.0, -1.5]     5
(-2.5, -2.0]     2
(2.0, 2.5]       1
(2.5, 3.0]       0
(-3.0, -2.5]     0
dtype: int64

### Question 17

- Show how to get a short summary of data in the numeric DataFrame?
- Show how to remove outliers (values which are too big or small)

#### Answer

In [12]:
# short answer: use df.describe() method

aa = ddd()
#display(aa)
display(aa.describe())
print("-"*40)

np.random.seed(12345)
df = pd.DataFrame(np.random.randn(1000, 4), columns=['A','B','C','D'])
print(df)
print("-"*40)
print(df.describe())
print("-"*40)
print(df.describe().index)  # [count, mean, std, min, 25%, 50%, 75%, max]
print("-"*40)

             ii        i1        i2        ff        f1        f2        xx          yy
count  6.000000  7.000000  7.000000  6.000000  7.000000  7.000000  7.000000    7.000000
mean   2.500000  3.000000  3.000000  3.000000  3.001764  4.915714  3.000000  209.991822
std    1.870829  2.160247  2.309401  2.366432  2.158556  3.130196  2.160247  107.949826
min    0.000000  0.000000  0.000000  0.000000  0.000000  1.110000  0.000000   61.150765
25%    1.250000  1.500000  1.000000  1.250000  1.506000  2.775000  1.500000  134.524656
50%    2.500000  3.000000  4.000000  3.000000  3.000300  4.440000  3.000000  209.389559
75%    3.750000  4.500000  4.500000  4.750000  4.500023  6.660000  4.500000  285.402467
max    5.000000  6.000000  6.000000  6.000000  6.000001  9.990000  6.000000  359.548186

----------------------------------------
            A         B         C         D
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
5   -0.539741  0.476985  3.248944 -1.021228
6   -0.577087  0.124121  0.302614  0.523772
7    0.000940  1.343810 -0.713544 -0.831154
8   -2.370232 -1.860761 -0.860757  0.560145
9   -1.265934  0.119827 -1.063512  0.332883
10  -2.359419 -0.199543 -1.541996 -0.970736
11  -1.307030  0.286350  0.377984 -0.753887
12   0.331286  1.349742  0.069877  0.246674
13  -0.011862  1.004812  1.327195 -0.919262
14  -1.549106  0.022185  0.758363 -0.660524
15   0.862580 -0.010032  0.050009  0.670216
16   0.852965 -0.955869 -0.023493 -2.304234
17  -0.652469 -1.218302 -1.332610  1.074623
18   0.723642  0.690002  1.001543 -0.503087
19  -0.622274 -0.921169 -0.726213  0.222896
20   0.051316 -1.157719  0.816707  0.433610
21   1.010737  1.824875 -0.997518  0.850591
22  -0.131578  0.912414  0.188211  2.169461
23  -0.114928  2.003697  0.029610  0.795253
24   0.118110 -0.748532  0.584970  0.152677
25  -1.565657 -0.562540 -0.032664 -0.929006
26  -0.482573 -0.036264  1.095390  0.980928
27  -0.589488  1.581700 -0.528735  0.457002
28   0.929969 -1.569271 -1.022487 -0.402827
29   0.220487 -0.193401  0.669158 -1.648985
..        ...       ...       ...       ...
970  1.140886  0.113279  0.206782 -1.460094
971 -1.523554 -0.590572 -0.324064  0.132262
972  0.097878  1.244456 -0.048534 -1.091849
973 -0.738296  0.115881  0.016253 -1.243078
974 -1.969172 -1.141360  0.405558 -0.521155
975 -0.813280 -0.461413  1.159668 -0.307670
976  0.669147  0.397355  0.612537  1.381155
977 -0.042541  1.182125  0.153036  0.075798
978  0.615651 -1.992291  0.963044  0.102469
979  0.359400  0.355787 -0.799366  1.120895
980 -0.261844 -0.474138 -0.112021 -0.285176
981 -0.136429  1.285628  0.753586  0.053410
982 -0.355393  0.790731  1.274794  0.233619
983 -1.316005  1.396082  0.336700  0.604880
984  0.675317 -0.060329  1.801953 -0.335099
985 -0.754114  0.650691  0.365401  1.367213
986 -0.105654 -0.001860  0.316802 -0.512542
987 -0.052736 -0.457225  2.452835 -1.050942
988 -0.172078  0.853049 -0.356263 -0.387002
989  0.881601  1.067288  1.079688  1.642339
990 -0.103672 -0.882949 -0.197357  1.336648
991  0.926782 -0.527103  0.633763  0.153988
992 -0.527754  0.815104 -0.677870 -1.466596
993  0.957144  0.377342 -0.383241  1.101972
994  1.221058 -0.326481  0.750008  0.604072
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]
----------------------------------------
                 A            B            C            D
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528
----------------------------------------
Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')
----------------------------------------

### Here is how to remove outliers

In [83]:
# look at outliers (numbers with abs. value more than 1.5)
df = pd.DataFrame(np.random.randn(10, 4), columns=['A','B','C','D'])
mask = np.abs(df) > 1.5
print("type of the mask is - ", type(mask))
print("Here is the mask:")
display(mask)
print("Here is the series showing for each row")
print("if it contains a True value in any column:")
display(df[mask].any(1)) # Ture if there is a True value in any column

# remove outliers - limit the value by 
print("-"*40)
df[mask] = np.sign(df) * 1.5
display(df)

type of the mask is -  <class 'pandas.core.frame.DataFrame'>
Here is the mask:

       A      B      C      D
0   True  False  False   True
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False   True  False
5  False  False  False  False
6  False  False  False  False
7  False  False  False  False
8   True  False  False  False
9   True  False  False  False

Here is the series showing for each row
if it contains a True value in any column:

0     True
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9     True
dtype: bool

----------------------------------------

          A         B         C         D
0  1.500000 -0.599052  0.133780 -1.500000
1 -0.113326  1.432697 -0.299660  0.280401
2  0.723167  0.642396 -1.254105  0.482604
3 -0.108060 -0.954252 -1.350434  0.233690
4  0.668536 -0.958679 -1.500000 -0.330040
5  1.101433 -1.212053  1.490393  1.230200
6  1.333844  0.959562 -0.219624  0.034404
7  0.915668  0.012254 -0.730117  0.270498
8  1.500000 -1.352859  0.295921  0.459361
9 -1.500000  0.737231  0.083112  0.102883

### Question 18

Show how to search and replace values in a column in a DataFrame

#### Answer

In [25]:
# most common way is in 2 steps:
#   step1 - create a mask to identify rows in which we need to do the change
#   step2 - do the change to the column using the mask
#   df.loc[mask,'col1'] = df.col1[mask] + df.col2[mask]

# alternative may be to use replace based on value(s)
#   df.col1.replace(list_of_values, replacing_value)
# or
#   df.col1.replace({val1:repl1, val2:repl2, etc.})

### Question 19

Difference between .apply() and .transform()

#### Answer

In [1]:
# it is described here:
# https://stackoverflow.com/questions/27517425/apply-vs-transform-on-a-group-object

# There are two major differences between 
# the transform and apply groupby methods.

# apply implicitly passes all the columns for each group 
# as a DataFrame to the custom function, 

# while transform passes each column for each group 
# as a Series to the custom function

# The custom function passed to apply 
# can return a scalar, or a Series or DataFrame 
# (or numpy array or even list). 

# The custom function passed to transform 
# must return a sequence (a one dimensional Series, array or list) 
# the same length as the group.

# So, transform works on just one Series at a time 
# and apply works on the entire DataFrame at once.

In [3]:
# Example
df = pd.DataFrame({'State':['Texas', 'Texas', 'Florida', 'Florida'], 
                   'a':[4,5,1,3], 'b':[6,10,3,11]})
display(df)

     State  a   b
0    Texas  4   6
1    Texas  5  10
2  Florida  1   3
3  Florida  3  11

In [5]:
def subtract_two(x):
    return x['a'] - x['b']

# The above function will not work with transform()
# because it references two columns
#      df.groupby('State').transform(subtract_two)
#      KeyError: ('a', 'occurred at index a')

# But it will work OK with apply():
df.groupby('State').apply(subtract_two)

State
Florida  2   -2
         3   -8
Texas    0   -2
         1   -5
dtype: int64

In [16]:
# Example of usage
df = pd.DataFrame({"c1":['shirt','shirt','pants','pants'],
                   "c2":['white','blue','black','brown'],
                   "amnt":[100,200,300,100]})
display(df)

      c1     c2  amnt
0  shirt  white   100
1  shirt   blue   200
2  pants  black   300
3  pants  brown   100

In [17]:
# lets index by c1,c2:
df = df.set_index(['c1','c2'])
display(df)

             amnt
c1    c2
shirt white   100
      blue    200
pants black   300
      brown   100

In [19]:
# now lets calculate the percentage of each color 
# for each clothing type (shirt or pants):
df = df.groupby(level=0).transform(lambda x: 100*x/x.sum())
display(df)

                  amnt
c1    c2
shirt white  33.333333
      blue   66.666667
pants black  75.000000
      brown  25.000000